services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DATABASE_URL=postgresql://user:password@postgres:5432/price_scraper
    depends_on:
      - redis
      - postgres
    volumes:
      - .:/app
    networks:
      - price-scraper-network

  worker:
    build: .
    command: celery -A price_scraper.worker.celery_app worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DATABASE_URL=postgresql://user:password@postgres:5432/price_scraper
    depends_on:
      - redis
      - postgres
    volumes:
      - .:/app
    networks:
      - price-scraper-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - price-scraper-network
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=price_scraper
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - price-scraper-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=False
    ports:
      - "5050:80"
    networks:
      - price-scraper-network
    volumes:
      - pgadmin_data:/var/lib/pgadmin

networks:
  price-scraper-network:
    driver: bridge

volumes:
  redis-data:
  postgres_data:
  pgadmin_data: 