version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    volumes:
      - .:/app
    networks:
      - price-scraper-network

  worker:
    build: .
    command: celery -A price_scraper.worker.celery_app worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    volumes:
      - .:/app
    networks:
      - price-scraper-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - price-scraper-network
    volumes:
      - redis-data:/data

networks:
  price-scraper-network:
    driver: bridge

volumes:
  redis-data: 